import streamlit as st

if "limba" not in st.session_state:
    st.session_state["limba"] = "RO"

if st.session_state["limba"] == "RO":
    st.title("⚖️ Termeni și Condiții de Utilizare")
    st.caption("Ultima actualizare: Iunie 2026 | Locație legală: Milton Keynes, UK")
    st.markdown("---")
    st.markdown("### 1. ACCEPTAREA TERMENILOR ȘI JURISDICȚIA EXCLUSIVĂ")
    st.markdown("Prin accesarea, vizitarea sau utilizarea acestui website, sunteți de acord în mod expres și necondiționat să respectați prezenții Termeni și Condiții, precum și legislația aplicabilă din Anglia și Țara Galilor (English Law). Orice dispută care nu poate fi soluționată amiabil va fi trimisă spre soluționare exclusivă instanțelor de judecată competente din Milton Keynes, Regatul Unit (United Kingdom). Acordul de utilizare se consideră semnat digital în momentul în care bifați activ căsuța de confirmare de pe pagina principală a Platformei.")
    st.markdown("### 2. NATURA SERVICIULUI (DISCLAIMER LEGAL CRITIC)")
    st.markdown("Acest website este un instrument experimental bazat pe algoritmi de Inteligență Artificială (Google Gemini API), administrat și deținut în totalitate de IULIAN ICHIM-UNGUREANU (Alias Pantick), operând din Milton Keynes, UK.")
    st.markdown("* **NU ESTE UN CABINET DE AVOCATURĂ:** Informațiile, traducerile, analizele de riscuri și sugestiile de renegociere generate de această Platformă au un scop strict informativ, orientativ și educațional.")
    st.markdown("* **FĂRĂ CONSULTANȚĂ JURIDICĂ:** Conținutul generat NU constituie, sub nicio formă, consultanță juridică autorizată, asistență legală, servicii de audit contractual sau opinii de specialitate în sensul Legii nr. 51/1995.")
    st.markdown("* **OBLIGAȚIA UTILIZATORULUI:** Utilizatorul poartă întreaga responsabilitate pentru decizia finală de a semna, modifica, respinge sau renegocia orice contract comercial. Se recomandă insistent consultarea unui avocat înainte de luarea oricărei decizii cu impact juridic sau financiar.")
    st.markdown("### 3. FINANȚARE, MONETIZARE ȘI DONAȚII (LINKTREE)")
    st.markdown("* **SCOPUL MONETIZĂRII:** Eventualele venituri realizate din reclame afișate (ex. Google AdMob) sunt destinate strict acoperirii costurilor de mentenanță și servere necesare funcționării Platformei.")
    st.markdown("* **DONAȚII PRIN PĂRȚI TERȚE:** Orice opțiune de donație accesibilă prin platforme externe (ex. Linktree) este complet voluntară. Fondurile pot fi redirecționate către entități terțe, fără ca acest lucru să confere utilizatorului statutul de client plătitor.")
    st.markdown("* **FĂRĂ SERVICII PREMIUM SAU UPGRADE-URI:** Efectuarea unei donații nu deblochează funcționalități suplimentare, beneficii sau upgrade-uri de performanță pe Platformă. Toți utilizatorii au acces la exact aceeași interfață.")
    st.markdown("### 4. GARANȚIA STRICTĂ DE NON-STOCARE A DATELOR")
    st.markdown("* **PROCESARE VOLATILĂ IN-MEMORY:** Documentele introduse și cheile API sunt procesate exclusiv în memoria temporară a browserului (sesiune). În momentul în care închideți tab-ul sau fereastra de browser, toate datele sunt șterse definitiv, instantaneu și irevocabil. Platforma nu deține baze de date pentru stocarea acestora.")
    st.markdown("### 5. LIMITAREA TOTALĂ A RĂSPUNDERII (DAMAGE CAP)")
    st.markdown("În măsura maximă permisă de legislația aplicabilă în Anglia și Țara Galilor (English Law):")
    st.markdown("* Administratorul nu va fi răspunzător în fața niciunui utilizator sau terț pentru nicio daună directă, indirectă, incidentă, specială, punitivă sau subsecventă rezultată din utilizarea, interpretarea sau încrederea acordată rapoartelor generate de AI.")
    st.markdown("* **PLAFON REZIDUAL DE SIGURANȚĂ:** Răspunderea totală cumulată a administratorului pentru orice pretenție apărută din sau în legătură cu utilizarea acestui site este limitată strict la o sumă fixă de **10 GBP (zece lire sterline)**, sumă recunoscută de utilizator ca fiind proporțională și echitabilă, eliminând riscul asociat prezenței reclamelor comerciale.")
    st.markdown("### 6. INDEMNIZARE, ANTI-HĂRȚUIRE ȘI CHELTUIELI DE JUDECATĂ")
    st.markdown("* **6.1. OBLIGAȚIA ÎN CAZ DE PROCESE NEFONDATE:** Dacă un utilizator inițiază o acțiune în instanță împotriva administratorului încălcând clauzele asumate, iar acțiunea sa este respinsă sau anulată, utilizatorul se obligă necondiționat să achite integral toate cheltuielile de judecată efectuate de administrator (onorariile avocaților/solicitors din UK implicați în apărare, taxele de curte, costurile de transport).")
    st.markdown("* **6.2. CLAUZĂ PENALĂ PENTRU CAMPANII DE DENIGRARE:** Utilizatorul se obligă să nu inițieze și să nu participe la nicio campanie publică de hărțuire, denigrare sau defăimare împotriva Platformei sau a administratorului (pe rețele sociale, forumuri sau Linktree). În caz de încălcare, în baza principiului daunelor pre-evaluate (Liquidated Damages), utilizatorul se obligă irevocabil să achite administratorului daune-interese în cuantum fix de **1.000 GBP pentru fiecare postare hărțuitoare distinctă**.")
    st.markdown("### 7. RENUNȚAREA LA PROCESE COLECTIVE (CLASS ACTION WAIVER)")
    st.markdown("Orice procedură se va desfășura strict pe bază individuală. Utilizatorul renunță în mod expres la dreptul de a participa ca reclamant sau membru într-un proces colectiv (Class Action) în fața oricărei instanțe din lume.")
    st.markdown("<br><hr><center style='color:#94a3b8; font-size:12px;'>🛡️ Asistent Contracte Freelanceri | Deținut de IULIAN ICHIM-UNGUREANU (Pantick)</center>", unsafe_allow_html=True)
else:
    st.title("⚖️ Terms and Conditions of Use")
    st.caption("Last Updated: June 2026 | Legal Venue: Milton Keynes, UK")
    st.markdown("---")
    st.markdown("### 1. ACCEPTANCE OF TERMS AND EXCLUSIVE JURISDICTION")
    st.markdown("By accessing, browsing, or using this website ('the Platform'), you expressly and unconditionally agree to comply with these Terms and Conditions and the applicable laws of England and Wales (English Law). Any dispute arising out of or in connection with these terms shall be submitted to the exclusive jurisdiction of the competent courts in Milton Keynes, United Kingdom. This agreement is legally deemed digitally executed the moment you actively check the confirmation box on the homepage.")
    st.markdown("### 2. NATURE OF THE SERVICE (CRITICAL LEGAL DISCLAIMER)")
    st.markdown("This website is an experimental tool based on Artificial Intelligence algorithms (Google Gemini API), fully owned and administered by **IULIAN ICHIM-UNGUREANU (Alias Pantick)**, operating from Milton Keynes, United Kingdom.")
    st.markdown("* **NOT A LAW FIRM:** The information, translations, risk analyses, and renegotiation suggestions generated by this Platform are for strictly informational, indicative, and educational purposes only.")
    st.markdown("* **NO LEGAL ADVICE:** The generated content DOES NOT, under any circumstances, constitute authorized legal advice, legal assistance, contract audit services, or professional legal opinions.")
    st.markdown("* **USER'S OBLIGATION:** The user bears sole and absolute responsibility for the final decision to sign, amend, reject, or renegotiate any commercial contract. It is strongly recommended to consult a qualified legal professional before making any decision with legal or financial impact.")
    st.markdown("### 3. FINANCING, MONETIZATION, AND DONATIONS (LINKTREE)")
    st.markdown("* **MONETIZATION PURPOSE:** Any revenue generated from ads (e.g., Google AdMob) is strictly used to cover maintenance and server costs.")
    st.markdown("* **THIRD-PARTY DONATIONS:** Any donation option via external platforms (e.g., Linktree) is entirely voluntary. Funds may be redirected to third parties or charitable causes, without conferring the status of a paying client.")
    st.markdown("* **NO PREMIUM SERVICES OR UPGRADES:** Making a donation does not unlock additional features, performance upgrades, or priority services on the Platform. All users access the exact same interface.")
    st.markdown("### 4. STRICT CONTRACTUAL DATA NON-STORAGE GUARANTEE")
    st.markdown("* **VOLATILE IN-MEMORY PROCESSING:** Uploaded documents and API keys are processed exclusively within the browser's temporary memory (session) and are permanently, instantly, and irrevocably deleted when the browser tab is closed. The Platform does not maintain databases to store this data.")
    st.markdown("### 5. TOTAL LIMITATION OF LIABILITY (DAMAGE CAP)")
    st.markdown("To the maximum extent permitted by applicable laws of England and Wales (English Law):")
    st.markdown("* The administrator shall not be liable to any user or third party for any direct, indirect, incidental, special, punitive, or consequential damages resulting from the use, interpretation, or reliance on reports generated by the AI.")
    st.markdown("* **RESIDUAL SAFETY CAP:** The total cumulative liability of the administrator for any claim arising out of or in connection with the use of this website is strictly limited to a fixed sum of **£10 GBP**, which the user agrees is fair and proportionate, considering the free-of-charge nature of this version.")
    st.markdown("### 6. INDEMNIFICATION, ANTI-HARASSMENT, AND LEGAL COSTS")
    st.markdown("* **6.1. REIMBURSEMENT FOR FRIVOLOUS LAWSUITS:** If a user initiates court action in breach of these waivers and the action is dismissed, they unconditionally agree to fully reimburse all legal costs incurred by the administrator (UK solicitors' fees, court fees, travel).")
    st.markdown("* **6.2. LIQUIDATED DAMAGES FOR ONLINE HARASSMENT:** Public campaigns of harassment, defamation, or disparagement against the Platform or the administrator (on social media, forums, or Linktree) are strictly prohibited. In case of breach, the user irrevocably agrees to pay fixed liquidated damages of **£1,000 GBP per distinct defamatory post**.")
    st.markdown("### 7. CLASS ACTION WAIVER")
    st.markdown("Proceedings will be conducted solely on an individual basis. The user waives the right to participate as a plaintiff or class member in any class action worldwide.")
    st.markdown("<br><hr><center style='color:#94a3b8; font-size:12px;'>🛡️ Freelancer Contract Assistant | Owned by IULIAN ICHIM-UNGUREANU (Pantick)</center>", unsafe_allow_html=True)
