import streamlit as st

if "limba" not in st.session_state:
    st.session_state["limba"] = "RO"

if st.session_state["limba"] == "RO":
    st.title("⚖️ Termeni și Condiții de Utilizare")
    st.caption("Ultima actualizare: Iunie 2026")
    st.markdown("---")
    st.markdown("### 1. ACCEPTAREA TERMENILOR")
    st.markdown("Prin accesarea, vizitarea sau utilizarea acestui website („Platforma”), sunteți de acord în mod expres și necondiționat să respectați prezenții Termeni și Condiții, precum și legislația aplicabilă. Dacă nu sunteți de acord cu oricare dintre aceste prevederi, aveți obligația de a înceta imediat utilizarea serviciului. Acordul de utilizare se consideră semnat digital în momentul în care bifați activ căsuța de confirmare de pe pagina principală a Platformei.")
    st.markdown("### 2. NATURA SERVICIULUI (DISCLAIMER LEGAL CRITIC)")
    st.markdown("Acest website este un instrument experimental bazat pe algoritmi de Inteligență Artificială (Google Gemini API), administrat și deținut în totalitate de **IULIAN ICHIM-UNGUREANU (Alias Pantick)**.")
    st.markdown("* **NU ESTE UN CABINET DE AVOCATURĂ:** Informațiile, traducerile, analizele de riscuri și sugestiile de renegociere generate de această Platformă au un scop strict informativ, orientativ și educațional.")
    st.markdown("* **FĂRĂ CONSULTANȚĂ JURIDICĂ:** Conținutul generat NU constituie, sub nicio formă, consultanță juridică autorizată, asistență legală, servicii de audit contractual sau opinii de specialitate în sensul Legii nr. 51/1995.")
    st.markdown("* **OBLIGAȚIA UTILIZATORULUI:** Utilizatorul poartă întreaga responsabilitate pentru decizia finală de a semna, modifica, respinge sau renegocia orice contract comercial. Se recomandă insistent consultarea unui avocat înainte de luarea oricărei decizii cu impact juridic sau financiar.")
    st.markdown("### 3. GARANȚIA STRICTĂ DE NON-STOCARE A DATELOR")
    st.markdown("Confidențialitatea documentelor dumneavoastră comerciale este prioritatea absolută a prezenților Termeni:")
    st.markdown("* **ABSENȚA BAZELOR DE DATE:** Platforma funcționează fără un modul de stocare de tip bază de date. Niciun server deținut de administrator nu colectează, nu salvează, nu arhivează și nu reține textul contractelor încărcate sau introduse manual.")
    st.markdown("* **PROCESARE VOLATILĂ IN-MEMORY:** Documentele dumneavoastră sunt procesate exclusiv în memoria temporară (sesiune) a browserului pe durata rulării analizei. În secunda în care închideți tab-ul sau fereastra de browser, toate textele încărcate sunt șterse definitiv, instantaneu și irevocabil.")
    st.markdown("### 4. LIMITAREA TOTALĂ A RĂSPUNDERII (DAMAGE CAP)")
    st.markdown("În măsura maximă permisă de legislația aplicabilă în România și la nivel internațional:")
    st.markdown("* Administratorul nu va fi răspunzător în fața niciunui utilizator sau terț pentru nicio daună directă, indirectă, incidentă, specială, punitivă sau subsecventă rezultate din utilizarea, interpretarea sau încrederea acordată rapoartelor generate de AI.")
    st.markdown("* **PLAFONAREA DAUNELOR:** Răspunderea totală cumulată a administratorului pentru orice pretenție apărută din sau în legătură cu utilizarea acestui site este limitată strict la suma de **10 GBP (zece lire sterline / echivalent lei)**, sumă recunoscută de utilizator ca fiind echitabilă, având în vedere caracterul gratuit al serviciului.")
    st.markdown("### 5. INDEMNIZARE ȘI SUPORTAREA CHELTUIELILOR DE JUDECATĂ")
    st.markdown("Utilizatorul se obligă să apere, să despăgubească și să exonereze de răspundere administratorul împotriva oricăror plângeri, daune, obligații, pierderi, costuri sau cheltuieli rezultate din interpretarea malițioasă sau greșită a rapoartelor Platformei.")
    st.markdown("* **ABUZUL DE DREPT ȘI PROCESELE FRIVOLE:** În cazul în care un utilizator inițiază o acțiune în instanță împotriva administratorului încălcând clauzele de exonerare asumate, iar acțiunea sa este respinsă sau realizată de magistrați, utilizatorul se obligă necondiționat prin prezentul contract să achite integral toate cheltuielile de judecată efectuate de administrator (onorariile avocaților implicați în apărare, taxele de timbru, expertizele și transportul aferent).")
    st.markdown("### 6. RENUNȚAREA LA PROCESE COLECTIVE (CLASS ACTION WAIVER)")
    st.markdown("Orice procedură de soluționare a unei dispute se va desfășura strict pe bază individuală. Utilizatorul renunță în mod expres la dreptul de a iniția sau de a participa ca reclamant sau membru într-un proces colectiv (Class Action), acțiune consolidată sau reprezentativă în fața oricărei instanțe din nicio jurisdicție mondială.")
    st.markdown("### 7. LEGEA APLICABILĂ ȘI JURISDICȚIA")
    st.markdown("Prezenții Termeni sunt guvernați și interpretați în conformitate cu legile din România. Orice dispută care nu poate fi soluționată amiabil va fi trimisă spre soluționare exclusivă instanțelor de judecată competente din România.")
    st.markdown("<br><hr><center style='color:#94a3b8; font-size:12px;'>🛡️ Asistent Contracte Freelanceri | Deținut de IULIAN ICHIM-UNGUREANU (Pantick)</center>", unsafe_allow_html=True)
else:
    st.title("⚖️ Terms and Conditions of Use")
    st.caption("Last Updated: June 2026")
    st.markdown("---")
    st.markdown("### 1. ACCEPTANCE OF TERMS")
    st.markdown("By accessing, browsing, or using this website ('the Platform'), you expressly and unconditionally agree to comply with these Terms and Conditions and all applicable laws. This agreement is legally deemed digitally executed the moment you actively check the confirmation box on the homepage.")
    st.markdown("### 2. NATURE OF THE SERVICE (CRITICAL LEGAL DISCLAIMER)")
    st.markdown("This website is an experimental tool based on Artificial Intelligence algorithms (Google Gemini API), fully owned and administered by **IULIAN ICHIM-UNGUREANU (Alias Pantick)**.")
    st.markdown("* **NOT A LAW FIRM:** The information, translations, risk analyses, and renegotiation suggestions generated by this Platform are for strictly informational, indicative, and educational purposes only.")
    st.markdown("* **NO LEGAL ADVICE:** The generated content DOES NOT, under any circumstances, constitute authorized legal advice, legal assistance, contract audit services, or professional legal opinions.")
    st.markdown("* **USER'S OBLIGATION:** The user bears sole and absolute responsibility for the final decision to sign, amend, reject, or renegotiate any contract. It is strongly recommended to consult a qualified legal professional before making any decision with legal or financial impact.")
    st.markdown("### 3. STRICT DATA NON-STORAGE GUARANTEE")
    st.markdown("The confidentiality of your commercial documents is the absolute priority of these Terms:")
    st.markdown("* **ABSENCE OF DATABASES:** The Platform operates without any database storage module. No server owned or controlled by the administrator collects, saves, archives, or retains the text of uploaded or manually entered contracts.")
    st.markdown("* **VOLATILE IN-MEMORY PROCESSING:** Your documents are processed exclusively within the temporary memory (session) of your browser during the live analysis. The exact second you close the browser tab or window, all uploaded texts are permanently, instantly, and irrevocably deleted.")
    st.markdown("### 4. TOTAL LIMITATION OF LIABILITY (DAMAGE CAP)")
    st.markdown("To the maximum extent permitted by applicable law internationally:")
    st.markdown("* The administrator shall not be liable to any user or third party for any direct, indirect, incidental, special, punitive, or consequential damages resulting from the use, interpretation, or reliance on reports generated by the AI.")
    st.markdown("* **DAMAGE PLAFOND:** The total cumulative liability of the administrator for any claim arising out of or in connection with the use of this website is strictly limited to the amount of **£10 GBP**, given the free-of-charge nature of this version.")
    st.markdown("### 5. INDEMNIFICATION AND LEGAL COSTS")
    st.markdown("The user agrees to defend, indemnify, and hold harmless the administrator against any complaints, damages, obligations, losses, costs, or expenses resulting from the malicious or incorrect interpretation of the Platform's reports.")
    st.markdown("* **ABUSE OF PROCESS AND FRIVOLOUS LAWSUITS:** If a user initiates any legal proceedings against the administrator in breach of the liability waivers assumed herein, and their action is dismissed, the user unconditionally agrees to fully reimburse all legal costs incurred by the administrator.")
    st.markdown("### 6. CLASS ACTION WAIVER")
    st.markdown("Any dispute resolution proceedings will be conducted solely on an individual basis. The user expressly and irrevocably waives the right to initiate, join, or participate as a plaintiff or class member in any class action worldwide.")
    st.markdown("### 7. GOVERNING LAW AND JURISDICTION")
    st.markdown("These Terms and Conditions are governed by and construed in accordance with the laws of Romania. Any dispute which cannot be resolved amicably shall be submitted to the exclusive jurisdiction of the competent courts in Romania.")
    st.markdown("<br><hr><center style='color:#94a3b8; font-size:12px;'>🛡️ Freelancer Contract Assistant | Owned by IULIAN ICHIM-UNGUREANU (Pantick)</center>", unsafe_allow_html=True)
